### PR TITLE
Don't add markup for missing help text, add 'for' attribute in label

### PR DESCRIPTION
**Pull request by saschpe**
Only a minor modification, empty <p> tags add unwanted space between form widgets. Also, I was so free to use 2 spaces for indenting ;-)

The second commit cleans up the code a bit, it removes some default-generated files and MANIFEST, a setuptools-generated file that is quite useless ;-)

The third one only adds "._.sw_" to .gitignore to hide VIM files.

The forth updates AppendedWidget and adds PrependedWidget and AppendPrependWidget. I'm not sure if the latter name is good. Also 'append_text' / 'prepend_text' allow arbitrary HTML to be passed (like '<i class="icon-envelope">'). Maybe this should be changed and a new attr like 'append_icon' / 'prepend_icon' be addded. This could also work with appended buttons....

The EmailInput should be of use in a HTML5 context and fails gracefully if the browser doesn't support it. AFAIR, only iphone & co treat it differently currently...

### CODE REVIEW

**Comment by calvinchengx** [comment]
+1

**Comment by pthrasher** [comment]
@saschpe I have cherry picked the first, and fourth of your above commits, and merged them in. Below are the merge commits:
347cd1cb66
964c54fb67

In the future, please observe the following rules:
- Don't remove files.
- Don't edit the .gitignore unless it fixes a bug in the framework. swap files should be ignored on your own computer using a global git ignore, not per project.
- Use 4 spaces when editing HTML, or Python.
- Pull down the latest before, and after making your commits so that your pull request can be automatically merged in.

Thanks for the contribution!

**Comment by saschpe** [comment]
Thanks for accepting, let's get through some of your issues though:
- Don't remove files.
  Uhm, I do ask myself why? The files models.py, tests.py and views.py are just the boilerplate stubs generated by ./manage.py startapp. Sure, AFAIR older Django releases expected those to be present (even if empty), but this isn't the case anymore, so why keeping them? Lastly, the file MANIFEST (not MANIFEST.in) is setuptools-generated boilerplate (I just tested it, distribute doesn't even seem to generate it anymore), IMO it's not really worth versioning.
- Don't edit the .gitignore
  Fair enough, a global .gitignore will do too ;-)
- Use 4 spaces ...
  No doubt about 4 spaces for Python, PEP8 and stuff, but I only idented HTML by 2 spaces. It is not only the recommended style for both Django templates and bootstrap code (not speaking of RoR and other frameworks), it also makes sense. Complex templates tend to eat up intendation rather fast, which may (or may not) be an issue for you. Anyways, it's subject to taste, so I don't have strong feelings about this.
- Pull down the latest before...
  I don't really know what you mean here? To me it looks like github's pull request generation code got it wrong, have a look at https://github.com/saschpe/django-bootstrap/commits/master, the commits are in perfect order ;-) If I may suggest something, don't use github's merge functionality, it's quite buggy and doesn't rebase. By doing it manually you have much more control:

$ git remote add saschpe git://github.com/saschpe/django-bootstrap.git
$ git fetch saschpe
$ git merge saschpe/master # while being on your local master branch
$ git rebase

Leaving this aside, I'd like to discuss the append_text / prepend_text parameters. I currently (ab)use them for passing HTML into the form template in order to render an icon in a PrependedWidget, but maybe we could come up with a more saner API?

Also, I'd like to propose putting your code in PyPI. Altough there are several other modules sharing or having a quite similar name. How about that?

**Comment by jterrace** [comment]
@saschpe see #38 for changing the name to put on pypi

**Comment by pthrasher** [comment]
@saschpe 

We'd appreciate it if you didn't make "sweeping" project changes in a single pull request. Additionally, changing project files (even if it's the removal of seemingly useless files) is something we can do. There is a lot of cleanup that needs to go into this project anyway. I'd like to do some of that, and discuss it prior to implementation. However, that's not a small change that can just be bundled with a pull request that solves something else.

Your commits had conflicts with other changes in the repo. This is due to you not having the latest commits in your fork. Prior to working on a feature, pull the latest from our copy (just add a remote), and merge it in. Once you're done with your work, and you have a few commits, do this again -- we may have merged in other pull requests that conflict with your code. Resolve any conflicts, and then submit the pull request. This way merging it much easier. I can't adequately resolve your merge conflicts as I didn't write the code.

As far as using 4 spaces... I don't have a problem with 2 spaces. I do however, have a problem with inconsistency, and all contributors need to stick with the conventions that are in place. If you'd like to change conventions, open an issue, and we'll discuss it, and change it everywhere all at once.

Thanks again for the contribution. It is appreciated. We need to get a good contribution rules doc in place. Also, I'd like to see this project fully support all form features in bootstrap 2.0. So we should work toward that.

**Pull request closed without merging**
