### PR TITLE
Added optional context for custom elements

### PR DESCRIPTION
**Pull request by tallowen**
This allows a customized context to be passed into the template. This
allows the form output to be changed dynamically based on a variable
that is passed in such as a request object to customized a form for each
user.

### CODE REVIEW

**Comment by tallowen** [comment]
@earle Was there a reason you closed this?

**Comment by earle** [comment]
Interesting..  I had merged it, but now dont see it.....

**Comment by tallowen** [comment]
I see it as an open pull request here: https://github.com/earle/django-bootstrap/pull/32

**Comment by calvinchengx** [comment]
+1

**Comment by pthrasher** [comment]
@tallowen Can you provide an example of how this would be used? That will be helpful in writing some docs up later. It doesn't have to be anything extravagant... just something very quick and dirty. Thanks! Also, please pull the latest, merge it into your branch, and push back up. This pull request as is cannot be automatically merged.

Thanks for the contribution! I'm helping maintain now, so responses should be a bit more prompt.

**Comment by pthrasher** [comment]
@tallowen bump?

**Comment by tallowen** [comment]
If bootstrap forms need to use a passed in variable to the template this library does not support that. (I.E. I wanted to change a photo upload form to show the current picture that was uploaded). I found this library that seemed to solve the problem of using bootstrap in a much more simple/flexible way for what I wanted to do:  https://github.com/tzangms/django-bootstrap-form

**Comment by pthrasher** [comment]
Thanks!

**Pull request closed without merging**
