### PR TITLE
Add documentation about the mixin class

### PR DESCRIPTION
**Pull request by borgstrom**
When I first started using django-bootstrap I was putting the Mixin as
the last class my form inherited from and it took me grok'ing the
existing code to realize that it needed to be placed first in the
inheritance chain.

### CODE REVIEW

**Comment by pthrasher** [comment]
Sweet! Thanks for the docs!

**Comment by jterrace** [comment]
I've been using this:

```
from django.contrib.auth.forms import PasswordChangeForm as OriginalPasswordChangeForm
class PasswordChangeForm(OriginalPasswordChangeForm, BootstrapForm):
    pass
```

and it's been working, but is it incorrect? Any problems with using this method?

**Comment by borgstrom** [comment]
@jterrace that's totally correct, if you don't define a `layout` in a `Meta` class then the form will just output all the fields on the form.

I personally like the legend, so I manually specified the `layout`

**Comment by jterrace** [comment]
Ah, I see. I understand now, thanks.

**Pull request merged**
